version: "3.8"

services:
  spaps-client:
    container_name: spaps-client
    build: '.'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spaps-client.rule=Host(`client-ml.the-displaycontrol.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.spaps-client.entrypoints=websecure"
      - "traefik.http.routers.spaps-client.tls.certresolver=myresolver"
      - "traefik.http.routers.spaps-client.service=spaps-client"
      - "traefik.http.services.spaps-client.loadbalancer.server.port=3000"
    networks:
      - traefik
networks:
  traefik:
    external: true
