version: "3.8"

services:
  company-landing:
    container_name: company-landing
    image: registry.it-flumx.com/company-landing:latest
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.company-landing.rule=Host(`it-flumx.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.company-landing.entrypoints=websecure"
      - "traefik.http.routers.company-landing.tls.certresolver=myresolver"
      - "traefik.http.routers.company-landing.service=company-landing"
      - "traefik.http.services.company-landing.loadbalancer.server.port=80"
    networks:
      - registry_default
networks:
  registry_default:
    external: true
